Added set support for arrays
ssciwr/ipywidgets-jsonschema pull request #117
Opened 2024-12-11 15:16 UTC by xshiki

2024-12-11 16:08 UTC, dokempf commented
The code looks good! Please add a test case in `tests/schemas` with a valid and an invalid document.

2024-12-11 16:08 UTC, dokempf commented
Also, for the future: If you write "This fixes #107" into the PR description, GitHub will automatically link it to the issue.

2024-12-12 14:06 UTC, xshiki commented
I've noticed that `set` is not a standard JSON schema validation keyword but `uniqueItems` with the same function already exists. But changing `set` to `unique_items` throws an error in the pydantic model.

```
from typing import List
class ListUnique(BaseModel):
    ids: List[str] = Field(unique_items=True)

form = Form(ListUnique.model_json_schema())
form.show()
```
```
PydanticUserError: `unique_items` is removed, use `Set` instead(this feature is discussed in https://github.com/pydantic/pydantic-core/issues/296)

For further information visit https://errors.pydantic.dev/2.9/u/removed-kwargs
```


For the test case so far
```
{
  "default": [],
  "schema": {
    "description": "Bla bla",
    "items": {
      "default": "foo",
      "type": "string"
    },
    "uniqueItems": true,
    "type": "array"
  },
  "valid": [
    [
      "foo"
    ],
    [
      "1",
      "2",
      "3"
    ]
  ],
  "invalid": [
    [
      "1",
      "1",
      "3"
    ]
  ]
}

```
So either the pydantic model throws an error or the test case fails when I use `  "set": true,  `
What's your opinion about this?

2025-01-14 16:24 UTC, dokempf requested changes

2025-01-14 16:24 UTC, dokempf commented on .DS_Store
This should not be part of the PR.

2025-01-14 16:24 UTC, dokempf commented on ipywidgets_jsonschema/.DS_Store
same.

2025-01-14 16:24 UTC, dokempf commented on ipywidgets_jsonschema/form.py
> +                    raise FormError("Array elements are not unique")
Looking at what `pydantic` does, I think it would also be acceptable to make the array unique instead of throwing an error:

```python
import pydantic
from typing import Set

class Foo(pydantic.BaseModel):
    ids: Set[str]

Foo(ids=["a", "a"])
```

above code outputs `Foo(ids={'a'})`

2025-01-14 16:24 UTC, dokempf commented on ipywidgets_jsonschema/form.py
> +            if schema.get("set", False):
I think there is a mix-up here of `set` and `uniqueItems`. `uniqueItems` is deprecated in a pydantic field definition, but it is still very much in the generated JSONSchema. `set` on the other hand does not exist in the JSONSchema spec - but `uniqueItems` does.

2025-01-21 15:02 UTC, dokempf approved these changes

2025-01-22 10:19 UTC, merged