Add optional descriptions
ssciwr/ipywidgets-jsonschema pull request #88
Opened 2023-11-09 08:08 UTC by tharwan

This PR adresses #86

2023-11-10 08:48 UTC, dokempf requested changes
This is looking good. My only concern is that it currently only applies to those widgets that went through `_construct_simple` - missing e.g. all formats, object and array. But then again, similar things can be said about tooltips, I guess. If you have the capacity to extend the feature to these additional types, feel free to do so. If you do not have it, I am also fine with merging as is, as it is an improvement over the status quo.

2023-11-10 08:48 UTC, dokempf commented on tests/test_form.py
> +@pytest.mark.parametrize("preconstruct", (0, 1))
No need to test this with this parametrization, as the two features do not interact.

2023-11-10 17:18 UTC, tharwan commented
> This is looking good. My only concern is that it currently only applies to those widgets that went through `_construct_simple` - missing e.g. all formats, object and array. But then again, similar things can be said about tooltips, I guess. If you have the capacity to extend the feature to these additional types, feel free to do so. If you do not have it, I am also fine with merging as is, as it is an improvement over the status quo.

I was not sure how to do it for the composed formats, but I also think it is most needed for the actual input fields which all go through the construct_simple.

2023-11-15 15:20 UTC, tharwan commented
I would be very happy if we could merge this soon.

2023-11-15 15:56 UTC, dokempf commented
@tharwan I implemented the missing types (array, object and datetime formats). With this change, I think I am ready to go.

2023-11-15 15:57 UTC, dokempf approved these changes

2023-11-15 15:57 UTC, merged